# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: Clojure Training
email: alex.miller@cognitect.com
description: > # this means to ignore newlines until "baseurl:"
  Clojure training materials and labs
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://cognitect.github.io/clojure-lab" # the base hostname & protocol for your site
twitter_username: cognitect
github_username:  cognitect

# Build settings
markdown: kramdown
